/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import genus.Funcoes;
import javax.swing.JOptionPane;

/**
 *
 * @author GilbertoSoares
 */
public class TelaLogin extends javax.swing.JFrame {
    /**
     * Creates new form TelaLogin
     */
    Funcoes funcoes;
    public TelaLogin() {
        funcoes = new Funcoes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAcessar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        passwordFieldSenha = new javax.swing.JPasswordField();
        jLabelLogo = new javax.swing.JLabel();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 400));
        getContentPane().setLayout(null);

        jButtonAcessar.setText("Acessar");
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(280, 200, 100, 30);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(170, 200, 80, 30);

        jLabelUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuário: ");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(60, 110, 80, 21);

        jLabelSenha.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(70, 150, 70, 21);

        textFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldUsuario);
        textFieldUsuario.setBounds(150, 110, 230, 30);

        passwordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(passwordFieldSenha);
        passwordFieldSenha.setBounds(150, 150, 230, 30);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(400, 90, 140, 160);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loginFundo.jpg"))); // NOI18N
        jLabelFundoLogin.setText("Senha:");
        jLabelFundoLogin.setPreferredSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(-5, 0, 560, 400);

        setSize(new java.awt.Dimension(548, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsuarioActionPerformed

    private void passwordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldSenhaActionPerformed

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        // TODO add your handling code here:
        
        if(textFieldUsuario.getText().equals("") || passwordFieldSenha.getPassword() == null){
            JOptionPane.showMessageDialog(this, "Campo(s) vazios.\n",
                "Erro ao efeturar login", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int idFuncionario;
        
        try {
            idFuncionario = Integer.parseInt(textFieldUsuario.getText());
        }
        catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Erro ao efetuar login!\n"
                    + "Usuário deve ser um ID.", "Erro ao buscar venda", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        char[] senhaChar;
        String senhaString = "";
        senhaChar = passwordFieldSenha.getPassword();
        String resultado;
        
        int tamanhoSenha = senhaChar.length;
        
        for (int i = 0; i < tamanhoSenha; i++) {
            senhaString += senhaChar[i];
        }
        
        resultado = funcoes.verificarLogin(idFuncionario, senhaString);
        
        if(resultado.equals("vendedor")){
            TelaVendedor tela = new TelaVendedor(idFuncionario);
            tela.setVisible(true);
            dispose();
        }
        else if(resultado.equals("gerente")){
            TelaGerente tela = new TelaGerente(idFuncionario);
            tela.setVisible(true);
            dispose();
        }
        else if(resultado.equals("nada")){
            JOptionPane.showMessageDialog(this, "Combinação de senha e ID inválida!\n",
                "Erro ao efeturar login", JOptionPane.ERROR_MESSAGE);
        
    }
        
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField passwordFieldSenha;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
