/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author GilbertoSoares
 */
public class TelaVendedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendedor
     */
    public static int idFuncionario;
    public TelaVendedor(int idFuncionario) {
        this.idFuncionario = idFuncionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPainelInterno = new javax.swing.JLabel();
        jLabelCadastrarProduto = new javax.swing.JLabel();
        jButtonVenda = new javax.swing.JButton();
        jLabelCadastrarProduto1 = new javax.swing.JLabel();
        jButtonCliente = new javax.swing.JButton();
        jLabelFundoVendedor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVenda = new javax.swing.JMenu();
        jMenuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelPainelInterno.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabelPainelInterno.setText("SISTEMA DE VENDAS");
        getContentPane().add(jLabelPainelInterno);
        jLabelPainelInterno.setBounds(70, 40, 390, 40);

        jLabelCadastrarProduto.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabelCadastrarProduto.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCadastrarProduto.setText("Realizar venda");
        getContentPane().add(jLabelCadastrarProduto);
        jLabelCadastrarProduto.setBounds(90, 260, 140, 14);

        jButtonVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/carrinho.png")));
        jButtonVenda.setToolTipText("Gerente");
        jButtonVenda.setFocusPainted(false);
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVenda);
        jButtonVenda.setBounds(120, 160, 80, 90);

        jLabelCadastrarProduto1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabelCadastrarProduto1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCadastrarProduto1.setText("Cadastrar cliente");
        getContentPane().add(jLabelCadastrarProduto1);
        jLabelCadastrarProduto1.setBounds(270, 260, 160, 14);

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png")));
        jButtonCliente.setToolTipText("Gerente");
        jButtonCliente.setFocusPainted(false);
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCliente);
        jButtonCliente.setBounds(310, 160, 80, 90);

        jLabelFundoVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoGeral.png"))); // NOI18N
        getContentPane().add(jLabelFundoVendedor);
        jLabelFundoVendedor.setBounds(0, 0, 550, 380);

        jMenuVenda.setText("Venda");

        jMenuItemRealizarVenda.setText("Realizar Venda");
        jMenuItemRealizarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemRealizarVendaMousePressed(evt);
            }
        });
        jMenuVenda.add(jMenuItemRealizarVenda);

        jMenuBar1.add(jMenuVenda);

        jMenuCliente.setText("Cliente");

        jMenuItemCadastrarCliente.setText("Cadastrar");
        jMenuItemCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCadastrarClienteMousePressed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCadastrarCliente);

        jMenuBar1.add(jMenuCliente);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(548, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        // TODO add your handling code here:
        TelaVenda tela = new TelaVenda(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente tela = new TelaCadastroCliente(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuItemCadastrarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteMousePressed
        // TODO add your handling code here:
        TelaCadastroCliente tela = new TelaCadastroCliente(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCadastrarClienteMousePressed

    private void jMenuItemRealizarVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemRealizarVendaMousePressed
        // TODO add your handling code here:
        TelaVenda tela = new TelaVenda(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemRealizarVendaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendedor(idFuncionario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JLabel jLabelCadastrarProduto;
    private javax.swing.JLabel jLabelCadastrarProduto1;
    private javax.swing.JLabel jLabelFundoVendedor;
    private javax.swing.JLabel jLabelPainelInterno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemRealizarVenda;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVenda;
    // End of variables declaration//GEN-END:variables
}
