/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author GilbertoSoares
 */
public class TelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerente
     */
    public static int idFuncionario;
    
    public TelaGerente(int idFuncionario) {
        this.idFuncionario = idFuncionario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonProduto = new javax.swing.JButton();
        jLabelCadastrarProduto = new javax.swing.JLabel();
        jButtonCategoria = new javax.swing.JButton();
        jLabelCadastrarCategoria = new javax.swing.JLabel();
        jLabelPaintelInternoCadastro = new javax.swing.JLabel();
        jLabelPainelInterno = new javax.swing.JLabel();
        buttonFuncionario = new javax.swing.JButton();
        jLabelCadastrarCategoria3 = new javax.swing.JLabel();
        buttonFornecedor = new javax.swing.JButton();
        jLabelCadastrarCategoria4 = new javax.swing.JLabel();
        jLabelFundoGerente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastroFuncionario = new javax.swing.JMenu();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuFornecedor = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        menuItemListarFuncionarios = new javax.swing.JMenuItem();
        menuItemListarProdutos = new javax.swing.JMenuItem();
        menuListarClientes = new javax.swing.JMenuItem();
        menuItemListarVendas = new javax.swing.JMenuItem();
        menuListarFaturas = new javax.swing.JMenuItem();
        menuDetalharVendas = new javax.swing.JMenuItem();
        menuDetalharFaturas = new javax.swing.JMenuItem();
        jMenuFaturas = new javax.swing.JMenu();
        menuAtualizarFornecedor = new javax.swing.JMenuItem();
        menuCriarFatura = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jButtonProduto.setToolTipText("Gerente");
        jButtonProduto.setFocusPainted(false);
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonProduto);
        jButtonProduto.setBounds(40, 180, 80, 90);

        jLabelCadastrarProduto.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabelCadastrarProduto.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCadastrarProduto.setText("Produto");
        getContentPane().add(jLabelCadastrarProduto);
        jLabelCadastrarProduto.setBounds(40, 280, 80, 20);

        jButtonCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categoria.png"))); // NOI18N
        jButtonCategoria.setToolTipText("Vendedor");
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCategoria);
        jButtonCategoria.setBounds(160, 180, 80, 90);

        jLabelCadastrarCategoria.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabelCadastrarCategoria.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCadastrarCategoria.setText("Categoria");
        getContentPane().add(jLabelCadastrarCategoria);
        jLabelCadastrarCategoria.setBounds(160, 280, 90, 20);

        jLabelPaintelInternoCadastro.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabelPaintelInternoCadastro.setForeground(new java.awt.Color(102, 102, 102));
        jLabelPaintelInternoCadastro.setText("CADASTRAR: ");
        getContentPane().add(jLabelPaintelInternoCadastro);
        jLabelPaintelInternoCadastro.setBounds(180, 120, 170, 40);

        jLabelPainelInterno.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        jLabelPainelInterno.setText("SISTEMA DE GERÊNCIA");
        getContentPane().add(jLabelPainelInterno);
        jLabelPainelInterno.setBounds(60, 40, 430, 40);

        buttonFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manager.png")));
        buttonFuncionario.setToolTipText("Vendedor");
        buttonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFuncionario);
        buttonFuncionario.setBounds(290, 180, 80, 90);

        jLabelCadastrarCategoria3.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabelCadastrarCategoria3.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCadastrarCategoria3.setText("Funcionário");
        getContentPane().add(jLabelCadastrarCategoria3);
        jLabelCadastrarCategoria3.setBounds(280, 280, 110, 20);

        buttonFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png")));
        buttonFornecedor.setToolTipText("Vendedor");
        buttonFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(buttonFornecedor);
        buttonFornecedor.setBounds(430, 180, 80, 90);

        jLabelCadastrarCategoria4.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabelCadastrarCategoria4.setForeground(new java.awt.Color(102, 102, 102));
        jLabelCadastrarCategoria4.setText("Fornecedor");
        getContentPane().add(jLabelCadastrarCategoria4);
        jLabelCadastrarCategoria4.setBounds(420, 280, 110, 20);

        jLabelFundoGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundoGeral.png"))); // NOI18N
        getContentPane().add(jLabelFundoGerente);
        jLabelFundoGerente.setBounds(0, 0, 550, 380);

        jMenuCadastroFuncionario.setText("Cadastrar");

        jMenuItemProdutos.setText("Produto");
        jMenuItemProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemProdutosMousePressed(evt);
            }
        });
        jMenuCadastroFuncionario.add(jMenuItemProdutos);

        jMenuItemCategoria.setText("Categoria");
        jMenuItemCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemCategoriaMousePressed(evt);
            }
        });
        jMenuCadastroFuncionario.add(jMenuItemCategoria);

        jMenuItemFuncionario.setText("Funcionário");
        jMenuItemFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemFuncionarioMousePressed(evt);
            }
        });
        jMenuCadastroFuncionario.add(jMenuItemFuncionario);

        jMenuFornecedor.setText("Fornecedor");
        jMenuFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuFornecedorMousePressed(evt);
            }
        });
        jMenuCadastroFuncionario.add(jMenuFornecedor);

        jMenuBar1.add(jMenuCadastroFuncionario);

        jMenuRelatorios.setText("Relatórios");

        menuItemListarFuncionarios.setText("Listar funcionários");
        menuItemListarFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemListarFuncionariosMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuItemListarFuncionarios);

        menuItemListarProdutos.setText("Listar produtos");
        menuItemListarProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemListarProdutosMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuItemListarProdutos);

        menuListarClientes.setText("Listar clientes");
        menuListarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuListarClientesMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuListarClientes);

        menuItemListarVendas.setText("Listar vendas");
        menuItemListarVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemListarVendasMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuItemListarVendas);

        menuListarFaturas.setText("Listar faturas");
        menuListarFaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuListarFaturasMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuListarFaturas);

        menuDetalharVendas.setText("Detalhar vendas");
        menuDetalharVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDetalharVendasMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuDetalharVendas);

        menuDetalharFaturas.setText("Detalhar faturas");
        menuDetalharFaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDetalharFaturasMousePressed(evt);
            }
        });
        jMenuRelatorios.add(menuDetalharFaturas);

        jMenuBar1.add(jMenuRelatorios);

        jMenuFaturas.setText("Fornecedor");

        menuAtualizarFornecedor.setText("Atualizar");
        menuAtualizarFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAtualizarFornecedorMousePressed(evt);
            }
        });
        jMenuFaturas.add(menuAtualizarFornecedor);

        menuCriarFatura.setText("Criar fatura");
        menuCriarFatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuCriarFaturaMousePressed(evt);
            }
        });
        jMenuFaturas.add(menuCriarFatura);

        jMenuBar1.add(jMenuFaturas);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(545, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        // TODO add your handling code here:
        TelaCadastroCategoria tela = new TelaCadastroCategoria(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        // TODO add your handling code here:
        TelaCadastroProduto tela = new TelaCadastroProduto(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        // TODO add your handling code here:
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void buttonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonFuncionarioActionPerformed

    private void jMenuItemProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemProdutosMousePressed
        // TODO add your handling code here:
        TelaCadastroProduto tela = new TelaCadastroProduto(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemProdutosMousePressed

    private void jMenuItemCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaMousePressed
        // TODO add your handling code here:
        TelaCadastroCategoria tela = new TelaCadastroCategoria(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCategoriaMousePressed

    private void jMenuItemFuncionarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioMousePressed
        // TODO add your handling code here:
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemFuncionarioMousePressed

    private void menuItemListarFuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemListarFuncionariosMousePressed
        // TODO add your handling code here:
        TelaListaFuncionarios tela = new TelaListaFuncionarios(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarFuncionariosMousePressed

    private void menuItemListarProdutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemListarProdutosMousePressed
        // TODO add your handling code here:
        TelaListaProdutos tela = new TelaListaProdutos(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarProdutosMousePressed

    private void jMenuFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFornecedorMousePressed
        // TODO add your handling code here:
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuFornecedorMousePressed

    private void menuAtualizarFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAtualizarFornecedorMousePressed
        // TODO add your handling code here:
        TelaAtualizaFornecedor tela = new TelaAtualizaFornecedor(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuAtualizarFornecedorMousePressed

    private void buttonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFornecedorActionPerformed
        // TODO add your handling code here:
        TelaCadastroFornecedor tela = new TelaCadastroFornecedor(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonFornecedorActionPerformed

    private void menuCriarFaturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCriarFaturaMousePressed
        // TODO add your handling code here:
        TelaCriarFatura tela = new TelaCriarFatura(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuCriarFaturaMousePressed

    private void menuItemListarVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemListarVendasMousePressed
        // TODO add your handling code here:
        TelaListaVendas tela = new TelaListaVendas(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarVendasMousePressed

    private void menuDetalharVendasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDetalharVendasMousePressed
        // TODO add your handling code here:
        TelaDetalhesVenda tela = new TelaDetalhesVenda(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuDetalharVendasMousePressed

    private void menuListarClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListarClientesMousePressed
        // TODO add your handling code here:
        TelaListaClientes tela = new TelaListaClientes(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuListarClientesMousePressed

    private void menuListarFaturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListarFaturasMousePressed
        // TODO add your handling code here:
        TelaListaFaturas tela = new TelaListaFaturas(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuListarFaturasMousePressed

    private void menuDetalharFaturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDetalharFaturasMousePressed
        // TODO add your handling code here:
        TelaDetalhesFatura tela = new TelaDetalhesFatura(idFuncionario);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuDetalharFaturasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente(idFuncionario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFornecedor;
    private javax.swing.JButton buttonFuncionario;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JLabel jLabelCadastrarCategoria;
    private javax.swing.JLabel jLabelCadastrarCategoria3;
    private javax.swing.JLabel jLabelCadastrarCategoria4;
    private javax.swing.JLabel jLabelCadastrarProduto;
    private javax.swing.JLabel jLabelFundoGerente;
    private javax.swing.JLabel jLabelPainelInterno;
    private javax.swing.JLabel jLabelPaintelInternoCadastro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastroFuncionario;
    private javax.swing.JMenu jMenuFaturas;
    private javax.swing.JMenuItem jMenuFornecedor;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenuItem menuAtualizarFornecedor;
    private javax.swing.JMenuItem menuCriarFatura;
    private javax.swing.JMenuItem menuDetalharFaturas;
    private javax.swing.JMenuItem menuDetalharVendas;
    private javax.swing.JMenuItem menuItemListarFuncionarios;
    private javax.swing.JMenuItem menuItemListarProdutos;
    private javax.swing.JMenuItem menuItemListarVendas;
    private javax.swing.JMenuItem menuListarClientes;
    private javax.swing.JMenuItem menuListarFaturas;
    // End of variables declaration//GEN-END:variables
}
